# Generated by Django 3.2.9 on 2021-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('entrada', models.DateField(verbose_name='Data de entrada do animal')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('prote', models.CharField(choices=[('pequeno', 'Pequeno'), ('médio', 'Médio'), ('grande', 'Grande')], max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('vacinas', models.CharField(max_length=50)),
                ('foto_animal', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=50)),
                ('imagem_campanha', models.ImageField(upload_to='img')),
            ],
        ),
    ]
