# Generated by Django 3.2.9 on 2021-11-29 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_campanha_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='data_evento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campanha',
            name='local_evento',
            field=models.CharField(default=1, max_length=50, verbose_name='Local do Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animaldomestico',
            name='raca',
            field=models.CharField(max_length=20, verbose_name='Raça'),
        ),
    ]
